<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OttawaWork.SelectFloors</RootNamespace>
    <AssemblyName>OttawaWork.SelectFloors</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\OttawaWork.Shared.csproj" />
  </ItemGroup>

</Project>
