<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BIMFlow.HighlightWalls</RootNamespace>
    <AssemblyName>BIMFlow.HighlightWalls</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\BIMFlow.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="HighlightWalls.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
