namespace BIMFlow.QuickAccessRibbon;

/// <summary>One row per catalog plugin — folder doubles as DLL name (BIMFlow.<Folder>.dll),
/// command class (BIMFlow.<Folder>.Command) and icon key (Icons/<Folder>_16.png), all by the
/// same established convention every plugin's own .csproj/Application.cs already follows.
/// Generated from plugins/src/*/Application.cs + data/plugins.json + data/plugin-impact.json —
/// see the git history for the generator script if this needs regenerating after adding a plugin.</summary>
public record RosterEntry(string Folder, string Panel, string Text, string Tooltip, bool Hero);

public static class PluginRoster
{
    public static readonly RosterEntry[] Entries =
    {
        new("BatchExporter", "Renumbering & Productivity", "Batch Exporter", "Export sheets or views to PDF, DWG, or NWC with a naming template.", true),
        new("BatchScheduleExporter", "Data & Coordination", "BatchScheduleExporter", "Export every schedule in the project to individual CSV files in one pass.", false),
        new("CSITakeoff", "Data & Coordination", "CSITakeoff", "Quantity takeoff grouped by Assembly Code, exported to CSV.", true),
        new("ConnectorAlign", "MEP & Structural", "ConnectorAlign", "Detect and fix misaligned or disconnected MEP connectors.", false),
        new("CropSync", "Sheets & Views", "Crop Sync", "Copy the crop region and view range from the active view to other views.", false),
        new("CrossProjectTransfer", "Data & Coordination", "CrossProjectTransfer", "Copy element types from one open Revit project into another.", false),
        new("DimensionAuto", "Sheets & Views", "DimensionAuto", "Auto-place dimension strings on walls, grids, and openings.", false),
        new("DimensionEditor", "Sheets & Views", "DimensionEditor", "Edit a dimension's override value, prefix, and suffix directly.", false),
        new("DoorWindowRenumber", "Renumbering & Productivity", "Door/Window Renumber", "Renumber doors or windows with a configurable scheme.", false),
        new("DuplicateFinder", "Model QA/QC & Cleanup", "Duplicate Finder", "Find overlapping or duplicate elements in the model.", true),
        new("ElementXRay", "Model QA/QC & Cleanup", "ElementX-Ray", "Diagnose why a selected element isn't visible in the active view.", false),
        new("EquipmentScheduler", "MEP & Structural", "EquipmentScheduler", "Generate equipment schedules linked to cut-sheet data.", false),
        new("Excel2Revit", "Data & Coordination", "Excel2Revit", "Two-way sync between Excel/CSV and Revit parameters or schedules.", false),
        new("ExcelAsDraft", "Data & Coordination", "ExcelAsDraft", "Import a CSV as a visual grid table in a drafting view, with one-click refresh.", false),
        new("FamilyAuditor", "Parameters & Families", "FamilyAuditor", "Scan families for best-practice issues before they ship.", false),
        new("FamilyFinder", "Parameters & Families", "FamilyFinder", "Audit loaded families by type count vs. placed instance count to find bloat.", false),
        new("FamilyLoaderPro", "Parameters & Families", "FamilyLoaderPro", "Batch-load every family in a folder, with conflict handling.", false),
        new("FamilyTypeManager", "Parameters & Families", "FamilyTypeManager", "Bulk rename, reorganize, and purge unused family types.", false),
        new("FramingChecker", "MEP & Structural", "FramingChecker", "Validate framing member connections, orientation, and cuts.", false),
        new("GridBubbleManager", "Sheets & Views", "Grid Bubbles", "Batch toggle grid and level bubble visibility.", false),
        new("GridGenerator", "MEP & Structural", "GridGenerator", "Auto-generate structural grids from CAD or Excel input.", false),
        new("GridRenumber", "Renumbering & Productivity", "Grid Renumber", "Batch rename grids or levels without breaking references.", false),
        new("HighlightWalls", "Highlight", "HighlightWalls", "Toggle an interior/exterior color highlight on every wall in the active view.", false),
        new("IFCExportQA", "Data & Coordination", "IFCExportQA", "Pre-flight checks and mapping presets for clean IFC exports.", false),
        new("InsulationManager", "MEP & Structural", "InsulationManager", "Batch-apply and update pipe/duct insulation by system rule.", false),
        new("LegendBuilder", "Sheets & Views", "LegendBuilder", "Auto-build a legend view from every detail component and annotation symbol actually used in the model.", false),
        new("LegendPlacer", "Sheets & Views", "LegendPlacer", "Place a legend on multiple sheets at a consistent position.", false),
        new("LegendUsageAudit", "Sheets & Views", "LegendUsageAudit", "Audit which line styles, fill patterns, and detail components are actually used — and how often.", false),
        new("LinkedModelAuditor", "Data & Coordination", "LinkedModelAuditor", "One dashboard for every linked model's status, worksets, and positioning.", false),
        new("MEPClashPrecheck", "MEP & Structural", "MEPClashPrecheck", "Lightweight interference check between MEP disciplines before formal coordination.", true),
        new("MaterialSwap", "Model QA/QC & Cleanup", "MaterialSwap", "Batch-swap a material across every compound-structure layer that uses it.", false),
        new("ModelCeilings", "Rooms", "ModelCeilings", "Auto-create drop ceilings from room boundaries in the active floor plan.", false),
        new("ModelHealthDashboard", "Model QA/QC & Cleanup", "ModelHealthDashboard", "Track file size, warning count, and element count trends over time.", false),
        new("NamingConventionAudit", "Model QA/QC & Cleanup", "NamingConventionAudit", "Check view, sheet, or family type names against a regex pattern you define.", false),
        new("OverriddenDimensions", "Model QA/QC & Cleanup", "OverriddenDimensions", "Find dimensions with a manually typed value override.", false),
        new("OverrideByParam", "Highlight", "Color Code", "Color-code any category by any parameter value, as real persistent view filters. Also exports PNG and clears its own filters.", true),
        new("ParamBatchEditor", "Parameters & Families", "ParamBatchEditor", "Bulk-edit parameter values in a spreadsheet-style grid.", false),
        new("ParameterFormulaPropagator", "Parameters & Families", "ParameterFormulaPropagator", "Generate parameter values from a template pattern and sequential numbering.", false),
        new("ParameterMapper", "Parameters & Families", "ParameterMapper", "Transfer parameter values between related elements by rule.", false),
        new("PlansPerRoom", "Rooms", "Plans Per Room", "Build a full room-data sheet set — floor plan, key plan, elevations, wall sections, RCP — with editable naming templates and per-room finish parameters.", true),
        new("PointCloudColorizer", "Highlight", "PC Color", "Tint point cloud instances with a preset or custom color, all in view or just the selection.", false),
        new("PointCloudHeatmap", "Highlight", "PC Heatmap", "Compare walls against point cloud scan data and color-code deviations: green/yellow/red by tolerance.", false),
        new("PurgePro", "Model QA/QC & Cleanup", "Purge Pro", "Repeat Revit's purge-unused until the model stops shrinking.", true),
        new("QCSummary", "Model QA/QC & Cleanup", "QCSummary", "One-click QA dashboard: unbounded rooms, disconnected walls, orphaned doors, sill consistency.", false),
        new("QuickSelect", "Renumbering & Productivity", "QuickSelect+", "Select elements by category and parameter-value rules.", true),
        new("RevisionTrack", "Sheets & Views", "RevisionTrack", "Automate revision clouds and revision schedules across sheet sets.", false),
        new("RoomColorFillPlan", "Rooms", "RoomColorFillPlan", "Color-fill the active plan view by any room parameter.", false),
        new("RoomFinishSchedule", "Rooms", "RoomFinishSchedule", "Generate a room finish schedule and export it to CSV.", false),
        new("RoomFinisher", "Model QA/QC & Cleanup", "RoomFinisher", "Find unplaced, unenclosed, and unbounded rooms before they bite you.", false),
        new("RoomHeightSync", "Rooms", "RoomHeightSync", "Batch-set room computation heights from a CSV.", false),
        new("RoomInventory", "Rooms", "RoomInventory", "List every element inside each room, with a category breakdown.", false),
        new("RoomRenumber", "Renumbering & Productivity", "Room Renumber", "Renumber rooms by direction of travel or zone.", false),
        new("RoomTagger", "Rooms", "RoomTagger", "Write each room's number/name onto every element found inside it.", false),
        new("ScheduleBlankDetector", "Model QA/QC & Cleanup", "ScheduleBlankDetector", "Find blank fields in a schedule and score how complete it is.", false),
        new("ScopeBoxSync", "Sheets & Views", "Scope Box Sync", "Apply a scope box to a batch of selected views.", false),
        new("SelectByCategory", "Renumbering & Productivity", "SelectByCategory", "One-click select every element of a category, in the view or the whole project.", false),
        new("SelectExteriorInterior", "Renumbering & Productivity", "SelectExteriorInterior", "Select every exterior or interior wall, door, or window in one click.", false),
        new("SharedCoordinatesAudit", "Data & Coordination", "SharedCoordinatesAudit", "Check whether every linked model's survey point actually lines up with this project's shared coordinates.", false),
        new("SharedParamSync", "Parameters & Families", "Shared Param Sync", "Diff and merge two shared parameter files.", true),
        new("SheetForge", "Sheets & Views", "SheetForge", "Batch-create sheets from an Excel list in one pass.", false),
        new("SheetListExporter", "Sheets & Views", "Sheet List", "Export or re-import the sheet list to/from CSV.", true),
        new("SlabHeightSync", "Rooms", "SlabHeightSync", "Batch-set Height Offset From Level across a set of floors.", false),
        new("StairCalculator", "Model QA/QC & Cleanup", "StairCalculator", "Check stair riser/tread proportions against the 2R+G comfort rule.", false),
        new("StandardsChecker", "Model QA/QC & Cleanup", "StandardsChecker", "Rule-based QA/QC audit against your firm's BIM standard.", false),
        new("SystemColorCoder", "MEP & Structural", "SystemColorCoder", "Auto color-code MEP systems by type and zone across every view.", false),
        new("TagAll", "Sheets & Views", "TagAll+", "Smart batch tagging with collision avoidance.", false),
        new("TextStyleAudit", "Sheets & Views", "Text Style Audit", "Scan the model for text and dimension styles outside the approved list.", true),
        new("TitleBlockUpdater", "Sheets & Views", "TitleBlockUpdater", "Batch-update title block info across sheets and linked projects.", false),
        new("UnplacedViewFinder", "Model QA/QC & Cleanup", "UnplacedViewFinder", "Find drawing views that aren't placed on any sheet.", false),
        new("ViewFilterCopy", "Sheets & Views", "Copy Filters", "Copy view filters and overrides from the active view to other views.", false),
        new("ViewMatrix", "Model QA/QC & Cleanup", "ViewMatrix", "Audit scope box and crop region settings across every view.", false),
        new("ViewRenamer", "Renumbering & Productivity", "View Renamer", "Batch rename views with find/replace, prefix/suffix, or regex.", false),
        new("ViewSync", "Sheets & Views", "ViewSync", "Reassign view templates across hundreds of views at once.", false),
        new("WallJoinFixer", "Model QA/QC & Cleanup", "Wall Join Fixer", "Batch-set wall join types and re-join nearby wall geometry.", false),
        new("WarningResolver", "Model QA/QC & Cleanup", "WarningResolver", "Triage and batch-fix common Revit warning categories.", false),
        new("WorksetMonitor", "Data & Coordination", "WorksetMonitor", "Live dashboard of workset ownership, sync times, and element counts.", false),
    };
}
