<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BIMFlow.PointCloudColorizer</RootNamespace>
    <AssemblyName>BIMFlow.PointCloudColorizer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\BIMFlow.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="PointCloudColorizer.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
