<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OttawaWork.HighlightExterior</RootNamespace>
    <AssemblyName>OttawaWork.HighlightExterior</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\OttawaWork.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="HighlightExterior.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
