<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>OttawaWork.SelectExtWalls</RootNamespace>
    <AssemblyName>OttawaWork.SelectExtWalls</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\OttawaWork.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SelectExtWalls.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
